services:
  python-brc:
    image: python-brc
    environment:
      ENV: prod
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/tmp
#    networks:
#      - backend
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.50'
          memory: 200M
#networks:
#  backend:
#    name: 1brc
#    external: true
